/*
 * This file is generated by jOOQ.
 */
package com.bank.moneytransfer.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transfer implements Serializable {

    private static final long serialVersionUID = -660177778;

    private UUID           id;
    private UUID           destinationAccountId;
    private UUID           sourceAccountId;
    private BigDecimal     amount;
    private Integer        status;
    private OffsetDateTime createdOn;

    public Transfer() {}

    public Transfer(Transfer value) {
        this.id = value.id;
        this.destinationAccountId = value.destinationAccountId;
        this.sourceAccountId = value.sourceAccountId;
        this.amount = value.amount;
        this.status = value.status;
        this.createdOn = value.createdOn;
    }

    public Transfer(
        UUID           id,
        UUID           destinationAccountId,
        UUID           sourceAccountId,
        BigDecimal     amount,
        Integer        status,
        OffsetDateTime createdOn
    ) {
        this.id = id;
        this.destinationAccountId = destinationAccountId;
        this.sourceAccountId = sourceAccountId;
        this.amount = amount;
        this.status = status;
        this.createdOn = createdOn;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getDestinationAccountId() {
        return this.destinationAccountId;
    }

    public void setDestinationAccountId(UUID destinationAccountId) {
        this.destinationAccountId = destinationAccountId;
    }

    public UUID getSourceAccountId() {
        return this.sourceAccountId;
    }

    public void setSourceAccountId(UUID sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(OffsetDateTime createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Transfer other = (Transfer) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (destinationAccountId == null) {
            if (other.destinationAccountId != null)
                return false;
        }
        else if (!destinationAccountId.equals(other.destinationAccountId))
            return false;
        if (sourceAccountId == null) {
            if (other.sourceAccountId != null)
                return false;
        }
        else if (!sourceAccountId.equals(other.sourceAccountId))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.destinationAccountId == null) ? 0 : this.destinationAccountId.hashCode());
        result = prime * result + ((this.sourceAccountId == null) ? 0 : this.sourceAccountId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transfer (");

        sb.append(id);
        sb.append(", ").append(destinationAccountId);
        sb.append(", ").append(sourceAccountId);
        sb.append(", ").append(amount);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
