/*
 * This file is generated by jOOQ.
 */
package com.bank.moneytransfer.jooq.tables.records;


import com.bank.moneytransfer.jooq.tables.Transfer;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferRecord extends UpdatableRecordImpl<TransferRecord> implements Record6<UUID, UUID, UUID, BigDecimal, Integer, OffsetDateTime> {

    private static final long serialVersionUID = -821063244;

    /**
     * Setter for <code>PUBLIC.TRANSFER.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.DESTINATION_ACCOUNT_ID</code>.
     */
    public void setDestinationAccountId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.DESTINATION_ACCOUNT_ID</code>.
     */
    public UUID getDestinationAccountId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.SOURCE_ACCOUNT_ID</code>.
     */
    public void setSourceAccountId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.SOURCE_ACCOUNT_ID</code>.
     */
    public UUID getSourceAccountId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.STATUS</code>.
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.CREATED_ON</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.CREATED_ON</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, BigDecimal, Integer, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, UUID, BigDecimal, Integer, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Transfer.TRANSFER.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Transfer.TRANSFER.DESTINATION_ACCOUNT_ID;
    }

    @Override
    public Field<UUID> field3() {
        return Transfer.TRANSFER.SOURCE_ACCOUNT_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Transfer.TRANSFER.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return Transfer.TRANSFER.STATUS;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Transfer.TRANSFER.CREATED_ON;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getDestinationAccountId();
    }

    @Override
    public UUID component3() {
        return getSourceAccountId();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getStatus();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getDestinationAccountId();
    }

    @Override
    public UUID value3() {
        return getSourceAccountId();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getStatus();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public TransferRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TransferRecord value2(UUID value) {
        setDestinationAccountId(value);
        return this;
    }

    @Override
    public TransferRecord value3(UUID value) {
        setSourceAccountId(value);
        return this;
    }

    @Override
    public TransferRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransferRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public TransferRecord value6(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TransferRecord values(UUID value1, UUID value2, UUID value3, BigDecimal value4, Integer value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferRecord
     */
    public TransferRecord() {
        super(Transfer.TRANSFER);
    }

    /**
     * Create a detached, initialised TransferRecord
     */
    public TransferRecord(UUID id, UUID destinationAccountId, UUID sourceAccountId, BigDecimal amount, Integer status, OffsetDateTime createdOn) {
        super(Transfer.TRANSFER);

        set(0, id);
        set(1, destinationAccountId);
        set(2, sourceAccountId);
        set(3, amount);
        set(4, status);
        set(5, createdOn);
    }
}
